---
ID: "512c911c-473a-420f-bd79-4e484be930b5"
Parent: "ddec7923-74b5-4c0c-86a6-04f551123581"
Template: "ddec7923-74b5-4c0c-86a6-04f551123581"
Path: "/sitecore/templates/Project/click-click-launch/Components/Search Experience/Search Experience Folder/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251217T062438Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\illia.kovalenko@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\illia.kovalenko@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8b792521-1c38-4006-baf1-15f87b426922"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\illia.kovalenko@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251217T062438Z
